# Generated by Django 4.1.2 on 2022-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_expectation',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='What I expect'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_general',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_looking',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Looking for'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone number'),
        ),
    ]
