# Generated by Django 4.1.2 on 2022-12-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_expectation',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='What I expect'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about_general',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about_looking',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Looking for'),
        ),
    ]
