# Generated by Django 4.1.2 on 2022-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='BRL', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount of currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('Não especificado', 'Não especificado'), ('Serviços Domésticos', 'Serviços Domésticos'), ('TI e Programação', 'TI e Programação'), ('Moda e Beleza', 'Moda e Beleza'), ('Reforma e Reparos', 'Reforma e Reparos'), ('Saúde', 'Saúde'), ('Assistência Técnica', 'Assistência Técnica'), ('Tradução e Conteúdo', 'Tradução e Conteúdo'), ('Design e Multimedia', 'Design e Multimedia')], default='Não especificado', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('standard', 'standard'), ('gold', 'gold'), ('platinum', 'platinum')], default='standard', max_length=10),
        ),
    ]
