# Generated by Django 4.1.2 on 2022-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_currency_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount of currency'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='(0) 0 0000-0000', max_length=16, verbose_name='Phone number'),
        ),
    ]
