# Generated by Django 4.1.2 on 2022-12-06 04:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_currency_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol')], default='Português', max_length=30),
        ),
    ]
