# Generated by Django 4.1.2 on 2022-12-06 20:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_about_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_advertisement',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Descrição do Anúncio:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='availability',
            field=models.TextField(blank=True, default='', max_length=70, verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço por hora'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol')], default='Português', max_length=30, verbose_name='Idiomas'),
        ),
    ]
